### ISSUE TITLE
SoapySDR has issues with HackRF

### ISSUE THREAD

**Issue by bobobo1618** [pothosware/SoapyOsmo#1]
This issue is unique to SoapySDR, other gr-osmosdr based tools like osmocom_fft work fine.

```
env LIBUSB_DEBUG=3 SoapySDRUtil --probe                                      ‹soapysdr-support*› [08:24:04] 
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device 
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:8510: device not responding (e00002ed). skipping device
Using HackRF One with firmware 2015.07.2 
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
Error probing device: Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB
```

**Comment by guruofquality** [comment]
Unfortunately, I don't have a hackrf to test this. I haven't updated the internal copy of gr-osmosdr because I think most of the recent work was covered by other soapy sdr modules. I thought that the recent hackrf work on gr-osmosdr was just for the "multi-device" wrapper. But there could have been other relevant fixes or updates if something changed in libhackrf...

Can you build soapy osmo from this branch? (its just an updated copy of gr-omosdr, it builds for me) https://github.com/pothosware/SoapyOsmo/tree/update_gr_osmo

Also, just to narrow down the problem to just this support module can you run with the driver filter

```
env LIBUSB_DEBUG=3 SoapySDRUtil --find="driver=hackrf"  
env LIBUSB_DEBUG=3 SoapySDRUtil --make="driver=hackrf"  
env LIBUSB_DEBUG=3 SoapySDRUtil --probe="driver=hackrf"
```

**Comment by guruofquality** [comment]
As a data point, a second user reported a similar error. I hope the recent gr-osmosdr fixes it, and FWIW the recent gr-osmosdr changes seem relevant to the problem. I'm looking for anyone that can test this update_gr_osmo branch, tell me if probe works:

```
#install SoapySDR
git clone https://github.com/pothosware/SoapySDR.git
cd SoapySDR
mkdir build && cd build
cmake ..
make -j4
sudo make install
sudo ldconfig #needed on debian systems
cd ..
cd ..

#install SoapyOsmo
git clone https://github.com/pothosware/SoapyOsmo.git
cd SoapyOsmo
#switch to the test branch
git checkout update_gr_osmo
mkdir build && cd build
cmake ..
#hackrf should be a configured component
make
sudo make install

#does it work?
SoapySDRUtil --probe="driver=hackrf"
```

**Comment by bobobo1618** [comment]
Afraid not. It's worth noting though that the other gr-osmosdr libraries and applications on my system are all built from Git (and those are the ones that work).

Is there an easy way to build using the system libraries? I couldn't see one.

Logs:

```
env LIBUSB_DEBUG=3 SoapySDRUtil --probe='driver=hackrf'                         ‹update_gr_osmo*› [16:30:17] 
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device driver=hackrf
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:8510: device not responding (e00002ed). skipping device
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:828c: pipe is stalled (e000404f). skipping device
Using HackRF One with firmware 2015.07.2 
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
Error probing device: Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB
```

**Comment by guruofquality** [comment]
So the gr-osmosdr in SoapyOsmo is just a copy of gr-osmosdr, and its the most recent from git on this branch: https://github.com/pothosware/SoapyOsmo/tree/update_gr_osmo/gr-osmosdr

We are reusing gr-osmosdr source for its consistent abstraction for several hardware devices,  but hooking in SoapySDR into the top level osmosdr stream and source and sink stuff -- so while the wrappers for devices like hackrf are identical, its still a different library at this point, we couldn't use the installed gr-osmosdr like that.

There's a few things we are doing that many of the gr-osmosdr apps don't. First, we are calling get_devices() and then making the device in the same process. Most apps just pass the args to the factory and never call get_devices(). So it could be that there is a bug with mismatched calls to hackrf_init/exit and/or hackrf_open/close.

Second, along the same lines, the SoapyOsmo wrapper is instantiating both a source and sink block in the same process. This might lead to multiple calls to hackrf_init or hackrf_open. Although I assume that people regularly have flow graphs with both source and sink in them -- it does seem that hackrf_init() would be getting called twice, and im not sure thats OK.

The only way to figure this out is probably to just add some prints before each hackrf_init/open/close/exit() call. That will give a nice dump before the error to see if that is indeed the problem or at least where it last was in the code before the error:
- https://github.com/pothosware/SoapyOsmo/blob/update_gr_osmo/gr-osmosdr/lib/hackrf/hackrf_source_c.cc
- https://github.com/pothosware/SoapyOsmo/blob/update_gr_osmo/gr-osmosdr/lib/hackrf/hackrf_sink_c.cc
- anyway -- be back in a bit with a diff or branch to try out...

I'm also curious if `SoapySDRUtil --find` is working ok

**Comment by guruofquality** [comment]
@bobobo1618 can send me the dump for the hackrf_prints branch: https://github.com/pothosware/SoapyOsmo/tree/hackrf_prints

Besides the extra calls to init and open, etc. I noticed that the sink implementation in terms of finding and making the device was a little different than the source, when they should be mirror images. It might be a worthwhile experiment to disable the sink side in SoapyOsmo, and see if probe works. Its a one line change:

```
diff --git a/GrOsmoSDRRegister.in.cpp b/GrOsmoSDRRegister.in.cpp
index 4f4e605..e66fce5 100644
--- a/GrOsmoSDRRegister.in.cpp
+++ b/GrOsmoSDRRegister.in.cpp
@@ -82,7 +82,7 @@ static SoapySDR::Device *make__@TARGET@(const SoapySDR::Kwargs &args)
     device->installSource(make_@TARGET@_source_c(params));
     #endif
     #if @HAS_SINK@
-    device->installSink(make_@TARGET@_sink_c(params));
+    //device->installSink(make_@TARGET@_sink_c(params));
     #endif

     //done
```

**Comment by bobobo1618** [comment]
Oh, I should add that the `could not retrieve device descriptor` errors are irrelevant. Those devices are my laptop's webcam and Bluetooth module.

Looks like the sink block is calling hackrf_open twice, once in the constructor and once in `get_devices`.

```
env LIBUSB_DEBUG=3 SoapySDRUtil --probe='driver=hackrf'                         ‹update_gr_osmo*› [20:53:05] 
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device driver=hackrf
Get devices init
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:828c: pipe is stalled (e000404f). skipping device
Get devices close
Sync block init?
Using HackRF One with firmware 2015.07.2 
Sink block sync init
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
Error probing device: Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB
```

Yes, `--find` works fine.

I'll get that dump and try that patch...

**Comment by bobobo1618** [comment]
Here's your dump:

```
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device driver=hackrf
get_devices:414 -- hackrf_init
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:828c: pipe is stalled (e000404f). skipping device
get_devices:449 -- hackrf_open
get_devices:467 -- hackrf_close
get_devices:480 -- hackrf_exit
hackrf_source_c:141 -- hackrf_init
hackrf_source_c:182 -- hackrf_open
Using HackRF One with firmware 2015.07.2 
hackrf_sink_c:191 -- hackrf_init
hackrf_sink_c:209 -- hackrf_open
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
Error probing device: Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB
```

Disabling the sink gives this:

```
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device driver=hackrf
get_devices:414 -- hackrf_init
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:828c: pipe is stalled (e000404f). skipping device
get_devices:449 -- hackrf_open
get_devices:467 -- hackrf_close
get_devices:480 -- hackrf_exit
hackrf_source_c:141 -- hackrf_init
hackrf_source_c:182 -- hackrf_open
Using HackRF One with firmware 2015.07.2 

----------------------------------------------------
-- Device identification
----------------------------------------------------
  driver=hackrf
  hardware=hackrf

----------------------------------------------------
-- Peripheral summary
----------------------------------------------------
  Channels: 1 Rx, 0 Tx
  Timestamps: NO

----------------------------------------------------
-- RX Channel 0
----------------------------------------------------
  Full-duplex: YES
  Antennas: TX/RX
  Full gain range: [0, 14] dB
    RF gain range: [0, 14] dB
    IF gain range: [0, 40] dB
    BB gain range: [0, 62] dB
  Full freq range: [4, 7246] MHz
    RF freq range: [4, 7246] MHz
    CORR freq range:  MHz
  Sample rates: [8, 20] MHz
  Filter bandwidths: [1.75, 28] MHz

libusb: warning [darwin_transfer_status] transfer error: device not responding (value = 0xe00002ed)
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 1
libusb: error [libusb_cancel_transfer] cancel transfer failed error -9
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 1
libusb: error [libusb_cancel_transfer] cancel transfer failed error -9
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 1
libusb: error [libusb_cancel_transfer] cancel transfer failed error -9
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 0 pipe 1
libusb: error [libusb_cancel_transfer] cancel transfer failed error -9
~hackrf_source_c:256 -- hackrf_close
~hackrf_source_c:268 -- hackrf_exit
```

**Comment by bobobo1618** [comment]
And it's worth noting that the osmosdr code has code that looks like it's intended to prevent exactly this, with every call to hackrf_init being wrapped in an if statement like this: https://github.com/pothosware/SoapyOsmo/blob/master/gr-osmosdr/lib/hackrf/hackrf_source_c.cc#L135

**Comment by guruofquality** [comment]
Except that _usage only prevents the source block from calling init more than once, or the sink block more than once. There is a separate _usage variable for both the source and sink wrapper -- maybe it should be the same global variable for both source and sink.

Perhaps if the hackrf_init() was properly protected (this calls the libusb context init btw), then the hackrf_open being duplicated would not be an issue... not sure. I can try to make the usage and its mutex a global variable...

I'm curious, but does anyone instantiate hackrf gr-osmosdr source and sink blocks for the same device? Like hackrf source and sink in the same GRC flowgraph? This issue would seem to indicate that this isnt possible.

I think this is going to end up with a patch for gr-osmosdr. I wouldn't mind the vindication :-)

**Comment by guruofquality** [comment]
@bobobo1618 I added this commit to hackrf_prints branch: https://github.com/pothosware/SoapyOsmo/commit/e4b2fcf49e8967661acfaf038884194adc286f2a

Its a global _usage count and mutex. Can you try this updated branch (without the little comment out the sink patch).

I think if hackrf_init is protected, which calls libusb_init, then the multiple calls to open should be ok. Just an eductaed guess....The libusb init has to be protected, we only want one single usb context. And FWIW, the underlying libusb calls are ok with multiple calls to libusb_open, which should use a reference count implementation.

**Comment by bobobo1618** [comment]
You work fast! The inits are working but it appears the opens have issues.

```
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device driver=hackrf
get_devices:414 -- hackrf_init
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:828c: pipe is stalled (e000404f). skipping device
get_devices:449 -- hackrf_open
get_devices:467 -- hackrf_close
get_devices:480 -- hackrf_exit
hackrf_source_c:141 -- hackrf_init
hackrf_source_c:182 -- hackrf_open
Using HackRF One with firmware 2015.07.2 
hackrf_sink_c:209 -- hackrf_open
libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
Error probing device: Failed to open HackRF device (-1000) HACKRF_ERROR_LIBUSB
```

**Comment by guruofquality** [comment]
@bobobo1618  New commit, shared device table -- hope this does the trick, at least a work around: https://github.com/pothosware/SoapyOsmo/commit/17262390ffde07b43d4321d8122bd050481c00ec

**Comment by bobobo1618** [comment]
Closer.

```
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device driver=hackrf
get_devices:420 -- hackrf_init
libusb: warning [darwin_cache_device_descriptor] could not retrieve device descriptor 05ac:828c: pipe is stalled (e000404f). skipping device
get_devices:455 -- hackrf_open
get_devices:473 -- hackrf_close
get_devices:486 -- hackrf_exit
hackrf_source_c:141 -- hackrf_init
hackrf_source_c:182 -- hackrf_open
Using HackRF One with firmware 2015.07.2 
hackrf_sink_c:210 -- hackrf_open
Using HackRF One with firmware 2015.07.2 
libusb: warning [darwin_transfer_status] transfer error: device not responding (value = 0xe00002ed)
Error probing device: Failed to start TX streaming (-6) HACKRF_ERROR_BUSY
```

**Comment by guruofquality** [comment]
The constructors also init streaming, which it seems both rx and tx cant be activated at the same time. So hackrf isnt full duplex, rf wise, but I thought the usb layer stuff basically was, seems to indicate that here: https://github.com/mossmann/hackrf/wiki/FAQ#a-14

There were start/stop hooks in the past to avoid this issue, they have been commented out. So this commit just restores them: https://github.com/pothosware/SoapyOsmo/commit/60daff7550d3f42848d8d553eb5d5169dc571257

**Comment by guruofquality** [comment]
Its probably time to make a SoapyHackRF -- just like the others. This could be handled a lot cleaner. 

And then, someone could use the SoapyHackRF in actual gr-osmosdr apps because of the Soapy support in gr-osmosdr, and then you can have a source and sink in the same flow graph -- still need to be careful with how start/stop are implemented because of the full duplex thing -- but it could be done. And the whole device handle reference counting thing is handled by SoapySDR, so the underlying hackrf stuff would be protected automatically.

**Comment by bobobo1618** [comment]
I left a comment on the commit. Other than removing the integer declarations, everything seems to work! Successfully started running CubicSDR running on top of it.

**Comment by bobobo1618** [comment]
Buuuut.... CubicSDR is getting terminated by SIGBUS when I set the bandwidth too high (above ~9MHz) or SIGSEGV if it doesn't crash immediately. Is that likely to be an issue here or with CubicSDR? Any logs I can help with?

**Comment by bobobo1618** [comment]
Ran it through lldb and got this:

```
Process 24928 stopped
* thread #10: tid = 0x22e75b, 0x0000000107c4a83c libhackrfSupport.so`hackrf_source_c::work(int, std::__1::vector<void const*, std::__1::allocator<void const*> >&, std::__1::vector<void*, std::__1::allocator<void*> >&) + 476, stop reason = EXC_BAD_ACCESS (code=1, address=0x1126fe000)
    frame #0: 0x0000000107c4a83c libhackrfSupport.so`hackrf_source_c::work(int, std::__1::vector<void const*, std::__1::allocator<void const*> >&, std::__1::vector<void*, std::__1::allocator<void*> >&) + 476
libhackrfSupport.so`hackrf_source_c::work:
->  0x107c4a83c <+476>: movq   %rdi, (%r13)
    0x107c4a840 <+480>: movzwl (%rsi), %edi
    0x107c4a843 <+483>: movq   0x18(%r15), %rbx
    0x107c4a847 <+487>: movq   (%rbx,%rdi,8), %rdi
```

**Comment by bobobo1618** [comment]
Aaand here it is with a debug build:

```
Set sample rate: 8000000
calculated optimal element count of 133632
Process 25322 stopped
* thread #9: tid = 0x22eebb, 0x0000000107be5aff libhackrfSupport.so`hackrf_source_c::work(this=0x0000000100e36310, noutput_items=133632, input_items=0x000000010210c3a0, output_items=0x000000010210c3b8) + 879 at hackrf_source_c.cc:401, stop reason = EXC_BAD_ACCESS (code=2, address=0x10867e000)
    frame #0: 0x0000000107be5aff libhackrfSupport.so`hackrf_source_c::work(this=0x0000000100e36310, noutput_items=133632, input_items=0x000000010210c3a0, output_items=0x000000010210c3b8) + 879 at hackrf_source_c.cc:401
   398      int remaining = noutput_items - _samp_avail;
   399  
   400      for (int i = 0; i < remaining; ++i)
-> 401        *out++ = _lut[ *(buf + i) ];
   402  
   403      _buf_offset = remaining;
   404      _samp_avail = (_buf_len / BYTES_PER_SAMPLE) - remaining;
```

**Comment by guruofquality** [comment]
Looks like bad bounds checking in hack rf source work(). So there is some internal temp buffer thats smaller than the input buffer according to the debug. So work is getting 133632, and the temp buffer defaults to 262144. Just a guess, not entirely sure whats going on here:

```
int remaining = noutput_items - _samp_avail;

    for (int i = 0; i < remaining; ++i)
      *out++ = _lut[ *(buf + i) ];
```

So I think it is running past the bounds of buf here.
Try increasing this by passing buffers=something_bigger into the device arguments

**Comment by cjcliffe** [comment]
A suitable replacement is now available at https://github.com/pothosware/SoapyHackRF and SoapyOsmo HackRF support is now disabled by default.
