### ISSUE TITLE
Conflicts with other Soapy modules

### ISSUE THREAD

**Issue by FFY00** [pothosware/SoapyOsmo#11]
SoapyOsmo seems to conflict with other Soapy modules.

SoapyOsmo:
  - `libairspySupport.so`
  - `libhackrfSupport.so`
  - `libosmosdrSupport.so`
  - `librfspaceSupport.so`
  - `librtlSupport.so`

SoapyAirspy:
  - `libairspySupport.so`

SoapyHackRF:
  - `libHackRFSupport.so`

SoapyRTLSDR:
  - `librtlsdrSupport.so`

Both SoapyOsmo and SoapyAirspy provide `libairspySupport.so`. SoapyOsmo also provides dynamic libraries for other devices but they don't conflict as they have slighter different names. I assume SoapyOsmo needs a SoapySDR module for each device it supports, but why not call them something like `libOsmo{Airspy,HackRF,RFSpacem,RtlSdr}Support.so`?

**Comment by guruofquality** [comment]
This whole project is meant to be phased out and has basically done so gradually. Those conflicts are projects that are disabled by default and now have dedicated projects to support their hardware. Did you see the table: https://github.com/pothosware/SoapyOsmo/wiki

PS - It looks like I can add rfspace to the list very soon

**Comment by FFY00** [comment]
Makes sense. I will disable them in the Arch package.
