### ISSUE TITLE
problem with return values in GrOsmoSDRStreamer::write

### ISSUE THREAD

**Issue by pavel-demin** [pothosware/SoapyOsmo#5]
I think that I've found a problem in `GrOsmoSDRStreamer::write`. It's the `if (ret == 0) ...` condition on line 66 in `GrOsmoSDRInterface.hpp`:
https://github.com/pothosware/SoapyOsmo/blob/master/GrOsmoSDRInterface.hpp#L66

If I'm not mistaken it's normal for a sink block to return 0 since it does not produce any samples (number of consumed samples is returned via `_consumed_total`).

I have a sink block (new version of `redpitaya_sink_c`) that returns 0 and works with GNU Radio but does not work with Pothos. When I modify this block to return `noutput_items`, it works with Pothos but does not work with GNU Radio.

**Comment by guruofquality** [comment]
For a sink block, it can either

1) return the number of samples consumed (example blade rf sink in gr-osmosdr)
or 2) call consume()/consume_each() and return 0  (example hack rf sink in gr-osmosdr)

Good catch. Its looks like the GrOsmoSDRInterface.hpp needs to support case 2. This should fix it:
- https://github.com/pothosware/SoapyOsmo/tree/fix_write_consume
- https://github.com/pothosware/SoapyOsmo/commit/445e60a000d0f84f0265180f110896a74042c4cf

**Comment by pavel-demin** [comment]
Thanks for fixing this problem!
I've just tested `fix_write_consume` branch with a new version of `redpitaya_sink_c`. The block now works with GNU Radio and with Pothos without any modifications.

**Comment by guruofquality** [comment]
Thanks for testing, fix merged. https://github.com/pothosware/SoapyOsmo/commit/f71fd99f55c9890f1b4da2dbbe39c689f038bca6
