### ISSUE TITLE
Add FCD support

### ISSUE THREAD

**Issue by LongnoseRob** [pothosware/SoapyOsmo#6]
Would be nice ot have funcube dongle also supported by SoapyOsmo.

I am trying to use SoapyOsmo&Remote for having a small ARM system running with the FCD attached at a good RF location and streaming the data over the netowrk to my main computer.
But unfortunately the fcd is not yet supported by SoapyOsmo/

**Comment by guruofquality** [comment]
The reason fcd source isnt supported yet is that the fcd and fcdplus are sort of outliers here. The fcd source in gr-osmosdr is just an empty block that is calling out to two external projects:
- https://github.com/gnuradio/gnuradio/tree/master/gr-fcd/lib
- https://github.com/dl1ksv/gr-fcdproplus

They arent very complicated blocks. It might be worth it for the manufacturer to make a dedicated fcd wrapper. Thats a best case, but short of that I might be able to copy in those two source trees and cobble something together. But I would need help testing as I dont have a fcd.

**Comment by LongnoseRob** [comment]
Thank you very much!

I am willingly to support you with testing the fcd stuff.

**Comment by guruofquality** [comment]
So this also pulls in all of gr-audio which is yet another even larger project. I was thinking, there is actually a soapy sdr project for audio devices, and it has hamlib support. So it might be better suited, though perhaps it might need some hooks to call the right things in hamlib.
- SoapyAudio https://github.com/pothosware/SoapyAudio/wiki
- Funcube in hamlib: https://github.com/N0NB/hamlib/blob/master/kit/funcube.h

@cjcliffe what do you think? Soapy audio for funcube w/ hamlib support.

**Comment by LongnoseRob** [comment]
I tried today the SoapyAudio part.
Short result it **works** _somehow_.

Long explanation:
built SoapyAudio with Hamblib support (Hamblib 3.0 and rtaudio were built and installed before).

Audio works, but the hamblib part does not support the FCD correctly, it requires 
rig=2513 (FCD hamlib ID)
rig_rate
and 
rig_port

but rigctl does not require rate or port when using rigctl -m 2513 because the FCD is working as a USB sound card and hid interface

@cjcliffe 
do you have a hint for me how work around the required setttings for rig_rate and rig_port?

The audio part works, but I need to do an I/Q calibration, any pointers how this goes into the SoapyAudioblock?

I think basically we could close this issue here and I can make a new one for the hamlib stuff in SoapyAudio

**Comment by cjcliffe** [comment]
@LongnoseRob not sure; I assumed hamlib would ignore those parameters if the device didn't use them; is it failing to open the device like that?   Also are you using the latest hamlib from GitHub? There are many recent devices in there that weren't in the port supplied OSX version.

Feel free to open up some issues at SoapyAudio; I think I'm going to get the sample offset thing fixed this weekend at least so I'll be in there tinkering.

**Comment by LongnoseRob** [comment]
@cjcliffe 
a. I am running on Arch Linux on x86_64 and armv7l --> no OSX here sorry
b. let me see if I can get some debugging information on the hamlib stuff

**Comment by bdn76** [comment]
I'm try to use four FCD pro on remote PC via CubicSDR/SoapyRemote/SoapyAudio:
1. How can i select FCD dongle? I'm see only one device - PulseAudio and can not specify sink (if i connect to remote PC via SSH then i can select FCD via switch audio sink but switch audio sink via SoapyRemote impossible).
2. FCD pro sample rate is 192k but only 96k may be selected via SoapyAudio.
3. I'm can not freq manipulate via hamlib - rigctl work (i'm can not specify FCD dongle, but i can see freq from first of all), but freq not show in CubicSDR.

**Comment by guruofquality** [comment]
@bdn76 There are some keyword arguments for SoapyAudio like rig, rig_port, rig_rate. I believe that these can be used to select the correct device and its parameters (not totally sure I dont have an FCD to test with). And you should be able to pass these same arguments through SoapyRemote.
- I recommend opening an issue on https://github.com/pothosware/SoapyAudio/issues
- Thinking to myself, we should document rig options on the wiki. And also, once the correct options are figured out, maybe the SoapyAudio could advertise a FCD device result to automate many of the arguments.

**Comment by bdn76** [comment]
Ok, thank you. [https://github.com/pothosware/SoapyAudio/issues/9] issue.

**Comment by troffasky** [comment]
I think you can close this one:
https://github.com/pothosware/SoapyFCDPP
