### ISSUE TITLE
add airspy support for bitpacking ?

### ISSUE THREAD

**Issue by ghost** [pothosware/SoapyOsmo#7]
For more details see:
http://git.osmocom.org/gr-osmosdr/commit/?id=164a09fc11cec2d8b15b38e8b512fa542d6cecc7

It is extremly similar to the three lines of code used to enable the BiasT

**Comment by guruofquality** [comment]
The gr-osmosdr submodule in the project should already have this commit. So isnt this already available as a device argument?

In anycase, when SoapyAirspy is complete, we get to deprecate airspy through SoapyOsmo. So we do need to get it working in SoapyAirspy reguardless.

**Comment by ghost** [comment]
Sorry you are right it does have it, I must have been looking an an older clone of SoapyOsmo. Thanks.
