### ISSUE TITLE
cannot find SoapySDR library in /usr/local/lib64

### ISSUE THREAD

**Issue by bogdanr** [pothosware/SoapyOsmo#8]
I have the SoarpySDR lib in `/usr/lib64` but it tries to look for it in a different path

I am building this with the following command:
`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLIB_INSTALL_DIR:PATH=lib64 -DLIB_SUFFIX=64 -DUSE_OSMO_RTLSDR=ON ..`
and I get this error:
```
-- Build type not specified: defaulting to release.
CMake Error at /usr/local/share/cmake/SoapySDR/SoapySDRConfig.cmake:161 (message):
  cannot find SoapySDR library in /usr/local/lib64
Call Stack (most recent call first):
  CMakeLists.txt:42 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by guruofquality** [comment]
I would be careful when transplating files like [this](https://github.com/pothosware/SoapySDR/issues/114) The directory for the cmake files matters as well. Can you configure and re-install SoapySDR also with `-DLIB_SUFFIX=64`?

**Comment by bogdanr** [comment]
Yes, I did that and also mentioned this in the wiki.

**Comment by guruofquality** [comment]
Oh maybe its the old install left in /usr/local. I dont think they can coexist in /usr and /usr/local, you might have to remove /usr/local cmake, libs, and includes

**Comment by bogdanr** [comment]
I actually forgot to close the issue after recompiling with that parameter. Thanks for the help! SoapySDR looks very interesting 👍
